# Sheldon configuration file
#
# See https://sheldon.cli.rs

shell = "zsh"

[templates]
defer = '''
    {{- hooks?.pre | nl }}
    {%- for file in files %}zsh-defer source "{{ file }}"{{ "\n" }}
    {%- endfor %}
    {{- hooks?.post | nl }}'''

# Completions
# -----------

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# Sourced
# -------

[plugins.local-0]
local = "~/.zsh/plugins"
use = ["{history,path}.plugin.zsh"]

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Deferred plugins
# ----------------

[plugins.autoenv]
github = "zpm-zsh/autoenv"
apply = ["defer"]

[plugins.local-1]
local = "~/.zsh/plugins"
use = ["{aliases*,gpg-agent,git,keybindings}.plugin.zsh"]
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]
hooks.pre = "export YSU_MODE=ALL"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

# This works best if it is placed last.
[plugins.compinit]
local = "~/.zsh/plugins"
apply = ["defer"]
