# Sheldon configuration file
#
# See https://sheldon.cli.rs

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
defer-more = "{% for file in files %}zsh-defer -t 0.5 source \"{{ file }}\"\n{% endfor %}"

# Completions
# -----------

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# Sourced
# -------

# The history plugin doesn't like being deferred, not sure why.
[plugins.history]
github = "ohmyzsh/ohmyzsh"
dir = "lib"

[plugins.path]
local = "~/.zsh/plugins"

[plugins.pure]
github = "rossmacarthur/pure"
use = ["{async,pure}.zsh"]

[plugins.wd]
github = "mfaerevaag/wd"
apply = ["fpath", "source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Deferred plugins
# ----------------

[plugins.autoenv]
github = "zpm-zsh/autoenv"
apply = ["defer"]

[plugins.aliases]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.gpg-agent]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.jetbrains]
profiles = ["jetbrains"]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,git,key-bindings,termsupport,theme-and-appearance}.zsh"]
apply = ["defer"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{copybuffer,git,pip}/*.plugin.zsh"]
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

# This works best if it is placed last.
[plugins.compinit]
local = "~/.zsh/plugins"
apply = ["defer"]

# Plugins that are even more deferred
# -----------------------------------

[plugins.pyenv]
local = "~/.zsh/plugins"
apply = ["defer-more"]
