# -- General -------------------------------------------------------------------

# Increase history limit
set -g history-limit 100000

# Terminal type configuration
# set -g default-command /bin/zsh
set-option -ga terminal-overrides ",*256c*:Tc"

# Sane scrolling
set -g mouse on

# -- Display -------------------------------------------------------------------

# Set window starting index to 1
set -g base-index 1

# Set pane starting index to 1
setw -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Rename window to reflect current program
setw -g automatic-rename on

# Monitor activity in other panes
set -g monitor-activity on

# Show wisual alert to activity in other pane
set -g visual-activity on

# Pane borders
set -g pane-active-border-style fg=color240
set -g pane-border-style fg=green

# Window modes style
set -g mode-style fg=color235,bg=green

# The text color of the active pane number in the window pane view
set -g display-panes-active-color magenta

# -- Status line -------------------------------------------------------------------

# The status line message style
set -g message-style fg=white,bg=magenta

# Status line message style
set -g message-command-style fg=color235,bg=magenta

# Status line for windows with an activity alert
set -g window-status-activity-style fg=white,bg=magenta

# Do not invert colors for the status line activity alert
set -g window-status-activity-style none

# Do not invert colors for the status line bell alert
set -g window-status-bell-style none

# Status line refresh interval
set -g status-interval 10

# Status line default foreground color
set -g status-fg white

# Status line default background color
set -g status-bg color234

# Left part of the status line shows session name, and in bold when C-t is pressed
set -g status-left "#[fg=color235,bg=green,bold]#{?client_prefix,#[bg=cyan],} \uEBC8 #(echo '#S' | tr '[:lower:]' '[:upper:]') #[fg=color239,bg=green]#{?client_prefix,#[bg=cyan],}\uE0BA"

# The window status line for the currently selected window
set -g window-status-current-format "#{?window_start_flag,#[fg=blue#,bg=color239],#[fg=blue#,bg=color235]}\uE0BA#[fg=white,bg=blue] \uE795 #W #{?window_end_flag,#[fg=color234#,bg=blue],#[fg=color235#,bg=blue]}\uE0BA"

# The window status line for the unselected windows
set -g window-status-format "#{?window_start_flag,#[fg=color235#,bg=color239],#[fg=color235#,bg=color235]}\uE0BA#[fg=color245,bg=color235] \uE795 #W #{?window_end_flag,#[fg=color234#,bg=color235],#[fg=color235#,bg=color235]}\uE0BA"

# Right part of the status line shows the username, and hostname
set -g status-right "#[fg=blue,bg=color234]\uE0B6#[fg=color234,bg=blue]\uF007 #[fg=white,bg=color237] #(whoami) #[fg=green,bg=color237]\uE0B6#[fg=color234,bg=green]\uF109 #[fg=color237,bg=green]\u2590#[fg=white,bg=color237]#h "

# The maximum length of the left hand part of the status line
set -g status-left-length 40

# The maximum length of the right hand part of the status line
set -g status-right-length 80

# No extra gap between window tabs; the chevrons provide the separation
set -g window-status-separator ""

# -- Shortcuts -------------------------------------------------------------------

# Set Ctrl-t as the default prefix key combination
set -g prefix C-t

# Synchronize panes bindings
bind I set-window-option synchronize-panes
bind i set-window-option synchronize-panes off

# Window split bindings
bind v split-window -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

# Window relayout bindings
bind V select-layout even-horizontal
bind H select-layout even-vertical

# Shortcut for reloading configuration
bind R source-file ~/.config/tmux/tmux.conf\; display "tmux.conf reloaded"
