#!/usr/bin/env zsh

# So these commands can be executed with sudo
alias sudo="sudo "

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# List hidden
alias lh="ls -a | egrep '^\.'"

# Use hub for git commands if it is installed
if hash hub >/dev/null 2>&1; then
  alias git=hub
fi

# So that Vim colors look correct in tmux
alias tmux="export TERM=xterm-256color; tmux"

# XOR text with key
alias xor="python -c 'from itertools import izip, cycle; import sys; sys.stdout.write(\"\".join(chr(ord(c) ^ ord(k)) for c, k in izip(sys.stdin.read(), cycle(sys.argv[1]))))'"

# Obfuscate text with a key
obf() {
  cat - | xor $1 | base64 | xz -c | xxd -ps
}

# Unobfuscate text with a key
unobf() {
  cat - | xxd -ps -r | xz -d | base64 --decode | xor $1
}

# Get ip netns information
ip_netns_prompt_info() {
  if (( $+commands[ip] )); then
    local ref="$(ip netns identify $$)"
    if [[ ! -z "$ref" ]]; then
      echo "($ref) "
    fi
  fi
}
