#!/usr/bin/env zsh

# Lock screen
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Trim trailing newline and copy to clipboard
alias copy="tr -d '\n' | pbcopy"

# Copy "¯\_(ツ)_/¯" to clipboard
shrug() {
  echo "¯\_(ツ)_/¯" | copy
  echo "Copied ¯\_(ツ)_/¯ to clipboard"
}

# Copy iTerm2 plist file back to .dotfiles
sync_iterm2_config() {
  rsync ~/Library/Preferences/com.googlecode.iterm2.plist ~/.dotfiles/iterm2/iterm2.plist
  plutil -convert xml1 ~/.dotfiles/iterm2/iterm2.plist
  echo "Synced ~/Library/Preferences/com.googlecode.iterm2.plist to ~/.dotfiles/iterm2/iterm2.plist"
}

# If there are no SSH keys in the agent, then call `ssh-add`
if ! ssh-add -l >/dev/null; then
  ssh-add >/dev/null 2>&1
fi
