#!/usr/bin/env zsh

# Default editor to Vim
export EDITOR=${EDITOR:-vim}

# Cargo env
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# Homebrew env
eval "$(/opt/homebrew/bin/brew shellenv)"

# Local bin
export PATH="$HOME/.local/bin:$PATH"

# Go
export GOPATH="$HOME/.go"
