#!/usr/bin/env zsh

# Locale
export LC_ALL=${LC_ALL:-en_US.UTF-8}

# Default editor to Vim
export EDITOR=${EDITOR:-vim}

# Homebrew env
eval "$(/opt/homebrew/bin/brew shellenv)"

# Local bin
export PATH="$HOME/.local/bin:$PATH"

# Cargo env
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# Go
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"
