#!/usr/bin/env zsh

# Default editor to Vim
export EDITOR=${EDITOR:-vim}

fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)

# Source all the things ✨
eval "$(sheldon source)"

# Local bin
if [ -d "$HOME/.local/bin" ]; then
    path_push "$HOME/.local/bin"
fi

# Cargo env
if [ -d "$HOME/.cargo" ]; then
    path_push "$HOME/.cargo/bin"
fi

# Go env
export GO111MODULE=on
export GOPATH="$HOME/.go"
if [ -d "$GOPATH" ]; then
    path_push "$GOPATH/bin"
fi
