#!/usr/bin/env zsh

# Default editor to Vim
export EDITOR=${EDITOR:-vim}

# Oh My Zsh / lib / history.zsh
export HIST_STAMPS="yyyy-mm-dd"
export HISTSIZE=250000
export SAVESIZE=25000

# You Should Use
export YSU_MODE=ALL

# Source all the things ✨
eval "$(sheldon source)"

# Local bin
[ -d "$HOME/.local/bin" ] && path_push "$HOME/.local/bin"

# Cargo env
[ -d "$HOME/.cargo" ] && path_push "$HOME/.cargo/bin"

# Go env
export GO111MODULE=on
export GOPATH="$HOME/.go"
[ -d "$GOPATH" ] && path_push "$GOPATH/bin"
