#!/usr/bin/env zsh

# IP addresses
alias ips="ifconfig -a | awk '/inet /{print \$2}'"

# Lock screen
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Trim trailing newline and copy to clipboard
alias copy="tr -d '\n' | pbcopy"

# Copy "¯\_(ツ)_/¯" to clipboard
shrug() {
  echo "¯\_(ツ)_/¯" | copy
  echo "Copied ¯\_(ツ)_/¯ to clipboard"
}
