#!/usr/bin/env zsh

# So these commands can be executed with sudo
alias sudo="sudo "

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# List hidden
alias lh="ls -a | egrep '^\.'"

# Use hub for git commands if it is installed
if hash hub >/dev/null 2>&1; then
  alias git=hub
fi

# So that Vim colors look correct in tmux
alias tmux="export TERM=xterm-256color; tmux"

# XOR text with key
alias xor="python -c 'from itertools import izip, cycle; import sys; sys.stdout.write(\"\".join(chr(ord(c) ^ ord(k)) for c, k in izip(sys.stdin.read(), cycle(sys.argv[1]))))'"

# Obfuscate text with a key
obf() {
  cat - | xor $1 | base64 | xz -c | xxd -ps
}

# Unobfuscate text with a key
unobf() {
  cat - | xxd -ps -r | xz -d | base64 --decode | xor $1
}

# IP addresses
ips() {
  ifconfig -a | python -c "
import re
import sys

try:
    from itertools import izip_longest as zip_longest
except ImportError:
    from itertools import zip_longest

matches = iter(re.split(r'((?:^|(?<=\n))[A-z0-9]+(?=:\s|\s+))', sys.stdin.read(), re.DOTALL)[1:])

interfaces = list()
for r in list(zip_longest(matches, matches)):
    ip_address = re.search(r'(?:(?<=inet addr:)|(?<=inet\s))\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', r[1])
    if ip_address:
        interfaces.append((r[0], ip_address.group(0)))

maximum_length = max(len(interface[0]) for interface in interfaces)
for interface in interfaces:
    sys.stdout.write('{1:<{0}}  {2}\n'.format(maximum_length, *interface))"
}

# Dev command
dev() {
  ttyresize
  dmesg -n 1 && echo 'set dmesg level to 1\n'
  stty speed 115200 -F /dev/ttyS1 >/dev/null && echo 'set /dev/ttyS1 speed to 115200\n'
}
