#!/usr/bin/env bash

# So these commands can be executed with sudo
alias sudo="sudo "

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# List hidden
alias lh="ls -a | egrep '^\.'"

# IP addresses
alias ips="ifconfig -a | awk '/inet addr/{print substr(\$2,6)}'"

# Lock screen
alias afk="gnome-screensaver-command -l"

# Shortcut for storepass script
alias sp="storepass"

# Shortcut for capslock script
alias cl="capslock"

# Set keyboard to Colemak
cm() {
  setxkbmap us -variant colemak
  xset r 66
  echo "Keyboard set to Colemak"
}

# Set keyboard to QWERTY
qw() {
  setxkbmap us
  xset -r 66
  echo "Keyboard set to QWERTY"
}

# Copy "¯\_(ツ)_/¯" to clipboard
shrug() {
  echo "¯\_(ツ)_/¯" | xclip -selection clipboard
  echo "Copied ¯\_(ツ)_/¯ to clipboard"
}

# Max brightness of Toshiba R850-12R laptop screen
maxbrightness() {
  sudo sh -c "echo 7 > /sys/class/backlight/acpi_video0/brightness"
  sudo sh -c "echo 255 > /sys/class/backlight/radeon_bl0/brightness"
}
