#!/usr/bin/env zsh

# So these commands can be executed with sudo
alias sudo="sudo "

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# List hidden
alias lh="ls -a | egrep '^\.'"

# IP addresses
alias ips="ifconfig -a | awk '/inet addr/{print substr(\$2,6)}'"

# So that Vim colors look correct in tmux
alias tmux="export TERM=xterm-256color; tmux"

# Shortcut for storepass script
alias sp="storepass"

# Dev command
dev() {
  ttyresize
  dmesg -n 1 && echo 'set dmesg level to 1\n'
  stty speed 115200 -F /dev/ttyS1 >/dev/null && echo 'set /dev/ttyS1 speed to 115200\n'
}
