#!/usr/bin/env zsh

export PATH=$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin

# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="rossmacarthur"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git sublime)
source $ZSH/oh-my-zsh.sh

# Custom
export EDITOR='nano'
if [ -f $HOME/.aliases ]; then
  source $HOME/.aliases
fi
