#!/usr/bin/env zsh

export PATH=$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin

# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="rossmacarthur"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git sublime)
source $ZSH/oh-my-zsh.sh

# Base16 Shell
BASE16_SHELL=$HOME/.config/base16-shell/
if [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ]; then
  eval "$($BASE16_SHELL/profile_helper.sh)"
fi

# Custom
export EDITOR='vim'
[ -f $HOME/.aliases     ] && source $HOME/.aliases
[ -f $HOME/.aliases.os  ] && source $HOME/.aliases.os
[ -f $HOME/.aliases.pvt ] && source $HOME/.aliases.pvt
