#!/usr/bin/env zsh

# Add extra folders to PATH
export PATH=$PATH:$HOME/.local/bin

# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh
export ZSH_THEME="rossmacarthur"
export DISABLE_AUTO_TITLE="true"
export COMPLETION_WAITING_DOTS="true"
export HIST_STAMPS="yyyy-mm-dd"

# Default plugins to enable
plugins=(general wd)
typeset -aU plugins

# Read extra plugins from files
if [ -f "$HOME/.plugins" ]
then
  plugins+=($(<"$HOME/.plugins"))
fi

source "$ZSH/oh-my-zsh.sh"

# Base16 Shell
export BASE16_SHELL=$HOME/.config/base16-shell/
if [ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ]
then
  eval "$("$BASE16_SHELL/profile_helper.sh")"
fi

# Source any extra aliases
if [ -f "$HOME/.aliases" ]
then
  source "$HOME/.aliases"
fi

# Set default editor to Vim
export EDITOR='vim'
