filetype plugin on       " Enable filetype detection
filetype indent on       " Set indent for current filetype
syntax enable            " Enable syntax highlighting
set termguicolors        " Fixes colors under tmux
set background=dark      " Use dark background
colorscheme slate

" Create undo directory if it doesn't exist
silent !mkdir -p ~/.vim/vimundo > /dev/null 2>&1

set nocompatible
set autoread      " Auto read when a file is changed from the outside
set number        " Show line numbers
set ruler         " Show current position
set nowrap        " Do not wrap lines
set expandtab     " Use spaces instead of tabs
set smarttab      " Tab are very smart
set shiftwidth=2  " 1 tab == 2 spaces
set tabstop=2     " 1 tab == 2 spaces
set autoindent    " Auto indent
set smartindent   " Indent are very smart
set nobackup      " Do not make temporary backup of file
set nowritebackup " Do not write temporary backup of file
set noswapfile    " Do not make a swap file for the buffer
set undofile      " Make undo's persist after exiting Vim
set undodir=~/.vim/vimundo/    " Set undo directory
set pastetoggle=<F2>           " Toggle for pasting
set backspace=indent,eol,start " Allow backspacing over everything in insert mode

" Delete trailing whitespace on save
func! DeleteTrailingWhitespace()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
autocmd BufWrite * :call DeleteTrailingWhitespace()

" Return to last edit position when opening files
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
